# Generated by Django 3.1.13 on 2022-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdb', '0004_alter_iphomedb_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iphomedb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
